language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.22.0

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y binutils-dev libunwind8-dev

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features "serde"
  - cargo build --verbose --features "fuzztarget"
  - if [ "$(rustup show | grep default | grep beta)" != "" ]; then cargo install --force cargo-web && cargo web build --target=asmjs-unknown-emscripten && cargo web test --target=asmjs-unknown-emscripten --nodejs; fi
  - if [ "$(rustup show | grep default | grep stable)" != "" ]; then cd fuzz && cargo test --verbose && ./travis-fuzz.sh; fi
