[package]
name = "bitcoin_hashes"
version = "0.1.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
documentation = "https://docs.rs/bitcoin-hashes/"
keywords = [ "crypto", "bitcoin", "hash", "digest" ]
readme = "README.md"

[lib]
name = "bitcoin_hashes"
path = "src/lib.rs"

[features]
default = []
unstable = []  # for benchmarking

[dev-dependencies]
serde_test = "1.0"

[dependencies]
byteorder = "1.2"

[dependencies.serde]
version = "1.0"
optional = true

